export const ADD_TODO="ADD_TODO"
export const DELETE_TODO="DELETE_TODO"
export const CHANGE_TODO="CHANGE_TODO"
export const EDIT_TODO="EDIT_TODO"
export const COMPLETED_TODO="COMPLETED_TODO"
export const GET_POST="GET_POST"